buildscript {
    repositories {
        google() // Required for Google services
        mavenCentral()
    }
    dependencies {
       classpath 'com.google.gms:google-services:4.4.2'
       classpath 'com.android.tools.build:gradle:7.0.2' // compatible version
        //classpath 'com.google.gms:google-services:4.4.2' // Update to the latest version
    }
}
allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
