name: mobile_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.10
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  device_preview: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter_native_splash:
  color: "#FFFFFF"  # Background color (white)
  android: true
  ios: true
  web: false
  fullscreen: true
  title:
    text: "Neuro Care"
    color: "#0000FF"  # Blue color for the text
    font_size: 32.0  # Adjust font size if needed
    font: "Arial"  # Customize font family if needed
  android_gravity: center  # Position the title

flutter:
  uses-material-design: true
